
--Ubicaciones de las paradas de los buses para la parte de dibujar las rutas
INSERT INTO ubicaciones_paradas VALUES ('Estacion universidades', 836, 2112);
INSERT INTO ubicaciones_paradas VALUES ('Estacion univalle', 725, 2067);
INSERT INTO ubicaciones_paradas VALUES ('Estacion holguines', 635, 1993);
INSERT INTO ubicaciones_paradas VALUES ('calle 13 con 84', 703, 1914);
INSERT INTO ubicaciones_paradas VALUES ('calle 13 con 70', 698, 1714);
INSERT INTO ubicaciones_paradas VALUES ('calle 13 con 66', 700, 1643);
INSERT INTO ubicaciones_paradas VALUES ('calle 13 con 50', 753, 1482);
INSERT INTO ubicaciones_paradas VALUES ('calle 13 con 39', 803, 1323);
INSERT INTO ubicaciones_paradas VALUES ('calle 13 con calle 14', 856, 1172);
INSERT INTO ubicaciones_paradas VALUES ('calle 13 con 15', 838, 972);
INSERT INTO ubicaciones_paradas VALUES ('Estacion san pascual', 875, 972);
INSERT INTO ubicaciones_paradas VALUES ('Estacion meledez', 616, 1922);
INSERT INTO ubicaciones_paradas VALUES ('calle 5ta con 81', 597, 1836);
INSERT INTO ubicaciones_paradas VALUES ('autopista con 70', 607, 1708);
INSERT INTO ubicaciones_paradas VALUES ('autopista con 54', 675, 1496);
INSERT INTO ubicaciones_paradas VALUES ('autopista con 45', 706, 1398);
INSERT INTO ubicaciones_paradas VALUES ('autopista con 32', 778, 1193);
INSERT INTO ubicaciones_paradas VALUES ('comfandi del prado', 987, 1077);
INSERT INTO ubicaciones_paradas VALUES ('autopista con calle 44', 1249, 1009);
INSERT INTO ubicaciones_paradas VALUES ('puente de los mil dias', 1403, 956);
INSERT INTO ubicaciones_paradas VALUES ('Estacion chiminangos', 1294, 390);
INSERT INTO ubicaciones_paradas VALUES ('Estacion flora industrial', 1219, 453);
INSERT INTO ubicaciones_paradas VALUES ('Estacion manzanares', 1110, 557);
INSERT INTO ubicaciones_paradas VALUES ('Estacion fatima', 1025, 654);
INSERT INTO ubicaciones_paradas VALUES ('Estacion avenida del rio', 910, 697);
INSERT INTO ubicaciones_paradas VALUES ('Estacion torre de cali', 811, 768);
INSERT INTO ubicaciones_paradas VALUES ('Estacion ermita', 836, 831);
INSERT INTO ubicaciones_paradas VALUES ('Estacion centro', 857, 893);
INSERT INTO ubicaciones_paradas VALUES ('Estacion santa librada', 752, 991);
INSERT INTO ubicaciones_paradas VALUES ('Estacion manzana del saber', 677, 1061);
INSERT INTO ubicaciones_paradas VALUES ('Estacion estadio', 609, 1155);
INSERT INTO ubicaciones_paradas VALUES ('Estacion tequendama', 567, 1249);
INSERT INTO ubicaciones_paradas VALUES ('Estacion unidad deportiva', 545, 1393);
INSERT INTO ubicaciones_paradas VALUES ('Estacion pampalinda', 565, 1537);
INSERT INTO ubicaciones_paradas VALUES ('Estacion caldas', 577, 1693);
INSERT INTO ubicaciones_paradas VALUES ('Estacion capri', 594, 1828);
INSERT INTO ubicaciones_paradas VALUES ('Estacion melendez', 617, 1926);
INSERT INTO ubicaciones_paradas VALUES ('Estacion nueva granada', 1118, 255);
INSERT INTO ubicaciones_paradas VALUES ('calle 70 con AV 4N', 1004, 216);
INSERT INTO ubicaciones_paradas VALUES ('calle 70 con AV 6N', 1004, 216);
INSERT INTO ubicaciones_paradas VALUES ('AV6N con calle 52N', 900,272);
INSERT INTO ubicaciones_paradas VALUES ('AV6N con calle 44N', 895, 389);
INSERT INTO ubicaciones_paradas VALUES ('AV6N con calle 37N', 873, 492);
INSERT INTO ubicaciones_paradas VALUES ('AV6N con calle 25N', 806, 593);
INSERT INTO ubicaciones_paradas VALUES ('AV6N con calle 18N', 800, 693);
INSERT INTO ubicaciones_paradas VALUES ('Estacion CAM', 768, 811);
INSERT INTO ubicaciones_paradas VALUES ('Estacion villa del sol', 1341, 321);
INSERT INTO ubicaciones_paradas VALUES ('Estacion metropolitano del norte', 148, 361);
INSERT INTO ubicaciones_paradas VALUES ('Estacion los guayacanes', 1462, 506);
INSERT INTO ubicaciones_paradas VALUES ('Estacion cali bella', 1510, 1656);
INSERT INTO ubicaciones_paradas VALUES ('Estacion las ceibas', 1480, 807);
INSERT INTO ubicaciones_paradas VALUES ('Estacion nueva floresta', 1342, 1078);
INSERT INTO ubicaciones_paradas VALUES ('Estacion villa blanca', 1288, 1178);
INSERT INTO ubicaciones_paradas VALUES ('Estacion la gran colombia', 1180, 1292);
INSERT INTO ubicaciones_paradas VALUES ('Estacion la colina', 1065, 1403);
INSERT INTO ubicaciones_paradas VALUES ('Estacion vila del sur', 944, 1522);
INSERT INTO ubicaciones_paradas VALUES ('Estacion ciudad 2000', 905, 1670);
INSERT INTO ubicaciones_paradas VALUES ('Estacion el ingenio', 894, 1855);


--Rutas iniciales
INSERT INTO ruta VALUES ('P10A', 'pretroncal', 'Estacion universidades,Estacion univalle,calle 13 con 84,calle 13 con 70,calle 13 con 66,calle 13 con 50,calle 13 con 39,calle 13 con calle 14,calle 13 con 15,Estacion san pascual');
INSERT INTO ruta VALUES ('P70B', 'pretroncal', 'Estacion universidades,Estacion univalle,calle 13 con 84,calle 13 con 70,calle 13 con 66,calle 13 con 50,calle 13 con 39,calle 13 con calle 14,comfandi del prado,autopista con calle 44');
INSERT INTO ruta VALUES ('P78B', 'pretroncal', 'Estacion universidades,Estacion univalle,Estacion holguines,Estacion meledez,calle 5ta con 81,autopista con 70,autopista con 54,autopista con 45,autopista con 32,comfandi del prado,autopista con calle 44,puente de los mil dias');
INSERT INTO ruta VALUES ('T31', 'troncal', 'Estacion chiminangos', 'Estacion flora industrial', 'Estacion manzanares', 'Estacion fatima', 'Estacion avenida del rio', 'Estacion torre de cali', 'Estacion ermita', 'Estacion centro', 'Estacion san pascual', 'Estacion santa librada', 'Estacion manzana del saber', 'Estacion estadio', 'Estacion tequendama', 'Estacion unidad deportiva', 'Estacion pampalinda', 'Estacion caldas', 'Estacion capri', 'Estacion melendez', 'Estacion holguines', 'Estacion univalle', 'Estacion universidades');
INSERT INTO ruta VALUES ('P60A', 'petroncal', 'Estacion nueva granada', 'calle 70 con AV 4N', 'calle 70 con AV 6N', 'AV6N con calle 52N', 'AV6N con calle 44N', 'AV6N con calle 37N', 'AV6N con calle 25N', 'AV6N con calle 18N', 'Estacion CAM', 'Estacion torre de cali', 'Estacion ermita', 'Estacion centro', 'Estacion san pascual');
INSERT INTO ruta VALUES ('T91', 'troncal', 'Estacion chiminangos', 'Estacion villa del sol', 'Estacion metropolitano del norte', 'Estacion los guayacanes', 'Estacion cali bella', 'Estacion las ceibas', 'puente de los mil dias', 'Estacion nueva floresta', 'Estacion villa blanca', 'Estacion la gran colombia', 'Estacion la colina', 'Estacion vila del sur', 'Estacion ciudad 2000', 'Estacion el ingenio', 'Estacion universidades');