/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controladores.ControladorTarjeta;
import Controladores.FabricaObjetos;
import Dibujar_recorrido.ControladorPintarRecorrido;
import Dibujar_recorrido.Dibujo;
import Dibujar_recorrido.Recorrido;
import Entidades.Ruta;
import Entidades.Tarjeta;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Label;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author giquo
 */
public class UIClientes extends javax.swing.JFrame {

    private Component uiParent;
    private FabricaObjetos fabrica;
    ControladorPintarRecorrido cpr;
    ArrayList<Recorrido> recorridos;
    ControladorTarjeta ct;
    /**
     * Creates new form UIClientes
     */
    public UIClientes(JFrame parent, FabricaObjetos fabricaObj) {
        initComponents();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        ct = new ControladorTarjeta(fabricaObj);
        uiParent = parent;
        uiParent.setVisible(false);
        fabrica = fabricaObj;
        cpr = new ControladorPintarRecorrido(fabrica);
        cpr.cargarParadasEnCombo(jComboBox1);
        cpr.cargarParadasEnCombo(jComboBox2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panMenu = new javax.swing.JPanel();
        panCenterMenu = new javax.swing.JPanel();
        panSaldo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panPlanearRuta = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bttnCalcularRuta = new javax.swing.JButton();
        bttnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panMenu.setLayout(new java.awt.BorderLayout());

        panCenterMenu.setLayout(new java.awt.BorderLayout());

        panSaldo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 10))); // NOI18N
        panSaldo.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("PIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        panSaldo.add(jLabel2, gridBagConstraints);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        panSaldo.add(jTextField1, gridBagConstraints);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        panSaldo.add(jButton1, gridBagConstraints);

        panCenterMenu.add(panSaldo, java.awt.BorderLayout.NORTH);

        panPlanearRuta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Planear Ruta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 10))); // NOI18N
        panPlanearRuta.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(jLabel3, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(jComboBox1, gridBagConstraints);

        jLabel4.setText("Fin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(jLabel4, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(jComboBox2, gridBagConstraints);

        panPlanearRuta.add(jPanel1, java.awt.BorderLayout.NORTH);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        panPlanearRuta.add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        bttnCalcularRuta.setText("Calcular Ruta");
        bttnCalcularRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCalcularRutaActionPerformed(evt);
            }
        });
        panPlanearRuta.add(bttnCalcularRuta, java.awt.BorderLayout.SOUTH);

        panCenterMenu.add(panPlanearRuta, java.awt.BorderLayout.CENTER);

        panMenu.add(panCenterMenu, java.awt.BorderLayout.CENTER);

        bttnAtras.setText("Atras");
        bttnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAtrasActionPerformed(evt);
            }
        });
        panMenu.add(bttnAtras, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panMenu, java.awt.BorderLayout.EAST);
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bttnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAtrasActionPerformed
        // TODO add your handling code here:
        uiParent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttnAtrasActionPerformed

    private void bttnCalcularRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCalcularRutaActionPerformed
        String origen = jComboBox1.getSelectedItem().toString();
        String destino = jComboBox2.getSelectedItem().toString();
        if (origen.equals(destino)) {
            JOptionPane.showMessageDialog(this, "El origen debe ser distinto al destino", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<Ruta> rutasQueCumplenRecorrido = cpr.buscarRutasRecorrido(origen, destino);
            if (rutasQueCumplenRecorrido.size()==0) {
                JOptionPane.showMessageDialog(this, "No hay ninguna ruta que realice el viaje "+origen+"-->"+destino);
            } else {
                recorridos = cpr.trazarRecorrido(rutasQueCumplenRecorrido, origen, destino);
                
                
                Dibujo dib = new Dibujo();
                Recorrido recorridoMasCorto = cpr.encontrarRecorridoMasCorto(recorridos);
                dib.setRecorrido(recorridoMasCorto);
                dib.setPreferredSize(new Dimension(1904, 3007));
                jScrollPane1.setColumnHeaderView(new Label(recorridoMasCorto.getNombreRuta()));
                jScrollPane1.getViewport().add(dib);
                
                String viajeString = "Rutas calculadas para el viaje\n"+origen+"-->"+destino+":";
                for (Recorrido recorrido : recorridos) {
                    DecimalFormat df = new DecimalFormat("#.###");
                    viajeString+="\n"+df.format(recorrido.getNombreRuta());
                }
                jTextArea1.setText(viajeString);
                
                /*
                for(int i=1; i<recorridos.size(); i++) {
                    int confirmCode = JOptionPane.showConfirmDialog(null, "Desea ver el siguiente recorrido");
                    
                    if (confirmCode==0) {
                        Dibujo dib2 = new Dibujo();
                        dib2.setRecorrido(recorridos.get(i));
                        dib2.setPreferredSize(new Dimension(1904, 3007));
                        jScrollPane1.getViewport().removeAll();
                        jScrollPane1.setColumnHeaderView(new Label(recorridos.get(i).getNombreRuta()));
                        jScrollPane1.getViewport().add(dib2);
                    }
                }
                */
            }
        }
    }//GEN-LAST:event_bttnCalcularRutaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String plata = " SELECT tar.saldo FROM tarjeta AS tar NATURAL JOIN venta_tarjeta WHERE pin_tarjeta = '"+tfSaldo.getText()+"';";
        
        
        //ConexionBD conect = new ConexionBD();
        Tarjeta tarjeta = ct.consultar(Integer.parseInt(jTextField1.getText()));
        //conect.abrirConexion();
        
        //String precio = conect.retornarString(plata);
        
        if( tarjeta == null )
            JOptionPane.showMessageDialog(this, "Pin Errado");
        else {
            int precio = tarjeta.getSaldo();
            JOptionPane.showMessageDialog(this, "Su saldo es de "+ precio + " Pesos");
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     * /
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         * /
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form * /
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIClientes().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAtras;
    private javax.swing.JButton bttnCalcularRuta;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panCenterMenu;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel panPlanearRuta;
    private javax.swing.JPanel panSaldo;
    // End of variables declaration//GEN-END:variables
}
