/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dibujar_recorrido;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Dibujo dib;
    public NewJFrame() {
        initComponents();
        dib = new Dibujo();
        
        ArrayList<ParadaBus> ubicaciones = new ArrayList();
        
        /*
        for (int i=0; i<5; i++) {
            int randomX = (int) ((Math.random()*600)+50);
            int randomY = (int) ((Math.random()*400)+50);
            ParadaBus ubicacion = new ParadaBus("Estacion" + (i+1), randomX, randomY );
            ubicaciones.add(ubicacion);
        }
        */
        ParadaBus ubicacion1 = new ParadaBus("Estacion univalle", 725, 2067);
        ParadaBus ubicacion2 = new ParadaBus("Estacion universidades", 836, 2112);
        ParadaBus ubicacion3 = new ParadaBus("calle 13 con 84", 703, 1914);
        ParadaBus ubicacion4 = new ParadaBus("calle 13 con 70", 698, 1714);
        ParadaBus ubicacion5 = new ParadaBus("calle 13 con 66", 700, 1643);
        ParadaBus ubicacion6 = new ParadaBus("calle 13 con 50", 753, 1482);
        ParadaBus ubicacion7 = new ParadaBus("calle 13 con 39", 803, 1323);
        ParadaBus ubicacion8 = new ParadaBus("calle 13 con calle 14", 856, 1172);
        ubicaciones.add(ubicacion2);
        ubicaciones.add(ubicacion1);
        ubicaciones.add(ubicacion3);
        ubicaciones.add(ubicacion4);
        ubicaciones.add(ubicacion5);
        ubicaciones.add(ubicacion6);
        ubicaciones.add(ubicacion7);
        ubicaciones.add(ubicacion8);
        dib.setUbicaciones(ubicaciones);
        dib.setPreferredSize(new Dimension(1904, 3007)); 
        jScrollPane1.getViewport().add(dib);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });
        jScrollPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jScrollPane1ComponentMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
        
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void jScrollPane1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1ComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
